# Pandas Tutorial

In [1]:
import pandas as pd

In [ ]:
#check pandas version
print(pd.__version__)

0.25.1


In [7]:
lst=[10,20,30,40]
myseries1 = pd.Series(lst)    
myseries1

0    10
1    20
2    30
3    40
dtype: int64

In [8]:
myseries1[0]

10

In [10]:
labels = ['a','b','c','d']

In [11]:
myseries2 = pd.Series(data = lst, index = labels)
myseries2

a    10
b    20
c    30
d    40
dtype: int64

In [12]:
myseries2['c']

30

In [16]:
ser1 = pd.Series(['south ','north ','south '])

In [17]:
ser2 = pd.Series(['africa','korea','korea'])

In [18]:
ser3 = ser1+ser2
ser3

0    south africa
1     north korea
2     south korea
dtype: object

In [19]:
lst = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]

In [20]:
lst

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]

In [21]:
dataframe = pd.DataFrame(lst)

In [22]:
dataframe

0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20

In [23]:
dataframe1 = pd.DataFrame(lst,columns = ["aa","bb","cc","dd","ee"], index=['row1','row2','row3','row4'])

In [24]:
dataframe1

aa  bb  cc  dd  ee
row1   1   2   3   4   5
row2   6   7   8   9  10
row3  11  12  13  14  15
row4  16  17  18  19  20

In [25]:
import numpy as np
arr1 = np.arange(16).reshape(4,4)

In [26]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
dataframe2 = pd.DataFrame(arr1,columns = "col1 col2 col3 col4".split(), index = "row1 row2 row3 row4".split())
dataframe2

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15

In [28]:
arr2= np.random.randint(100, size = (5,5))

In [29]:
arr2

array([[16, 15, 97, 88, 65],
       [46,  7, 27, 53, 99],
       [80,  5, 53, 11, 38],
       [42, 55, 26, 56, 94],
       [30, 59, 80, 66, 73]])

In [30]:
dataframe3 = pd.DataFrame(arr2,columns = " Sub1 Sub2 Sub3 Sub4 Sub5 ".split(), index = "Stud1 Stud2 Stud3 Stud4 Stud5".split())
dataframe3

Sub1  Sub2  Sub3  Sub4  Sub5
Stud1    16    15    97    88    65
Stud2    46     7    27    53    99
Stud3    80     5    53    11    38
Stud4    42    55    26    56    94
Stud5    30    59    80    66    73

In [31]:
data = dataframe3
data

Sub1  Sub2  Sub3  Sub4  Sub5
Stud1    16    15    97    88    65
Stud2    46     7    27    53    99
Stud3    80     5    53    11    38
Stud4    42    55    26    56    94
Stud5    30    59    80    66    73

In [32]:
data['Sub1']

Stud1    16
Stud2    46
Stud3    80
Stud4    42
Stud5    30
Name: Sub1, dtype: int64

In [33]:
data.loc['Stud1']

Sub1    16
Sub2    15
Sub3    97
Sub4    88
Sub5    65
Name: Stud1, dtype: int64

In [34]:
data.iloc[0]
#find difference between iloc and loc

Sub1    16
Sub2    15
Sub3    97
Sub4    88
Sub5    65
Name: Stud1, dtype: int64

In [35]:
data.iloc[1]

Sub1    46
Sub2     7
Sub3    27
Sub4    53
Sub5    99
Name: Stud2, dtype: int64

In [36]:
data.iloc[2] 

Sub1    80
Sub2     5
Sub3    53
Sub4    11
Sub5    38
Name: Stud3, dtype: int64

In [37]:
data.iloc[1:3]  

Sub1  Sub2  Sub3  Sub4  Sub5
Stud2    46     7    27    53    99
Stud3    80     5    53    11    38

In [38]:
data.iloc[::2]

Sub1  Sub2  Sub3  Sub4  Sub5
Stud1    16    15    97    88    65
Stud3    80     5    53    11    38
Stud5    30    59    80    66    73

In [39]:
data.iloc[3:, 3:]

Sub4  Sub5
Stud4    56    94
Stud5    66    73

In [40]:
data.iloc[2:, 2:]

Sub3  Sub4  Sub5
Stud3    53    11    38
Stud4    26    56    94
Stud5    80    66    73

In [41]:
data.iloc[:,4]

Stud1    65
Stud2    99
Stud3    38
Stud4    94
Stud5    73
Name: Sub5, dtype: int64

In [42]:
data.iloc[:,-1]

Stud1    65
Stud2    99
Stud3    38
Stud4    94
Stud5    73
Name: Sub5, dtype: int64

In [43]:
df = pd.DataFrame(np.random.randint(20,30,16).reshape(4,4),"rr1 rr2 rr3 rr4".split(), "cc1 cc2 cc3 cc4".split())

In [44]:
df

cc1  cc2  cc3  cc4
rr1   29   25   25   20
rr2   22   24   24   20
rr3   29   26   24   29
rr4   24   24   23   21

In [45]:
df.head()

cc1  cc2  cc3  cc4
rr1   29   25   25   20
rr2   22   24   24   20
rr3   29   26   24   29
rr4   24   24   23   21

In [46]:
df.head(2)

cc1  cc2  cc3  cc4
rr1   29   25   25   20
rr2   22   24   24   20

In [47]:
#tail - will give last 5 rows
df.tail()

cc1  cc2  cc3  cc4
rr1   29   25   25   20
rr2   22   24   24   20
rr3   29   26   24   29
rr4   24   24   23   21

In [48]:
#last 2 rows
df.tail(2)

cc1  cc2  cc3  cc4
rr3   29   26   24   29
rr4   24   24   23   21

In [49]:
#info() - will give datatype of each column
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, rr1 to rr4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cc1     4 non-null      int64
 1   cc2     4 non-null      int64
 2   cc3     4 non-null      int64
 3   cc4     4 non-null      int64
dtypes: int64(4)
memory usage: 160.0+ bytes


In [50]:
#describe() - all statistical information related to dataset
df.describe()

cc1        cc2        cc3        cc4
count   4.000000   4.000000   4.000000   4.000000
mean   26.000000  24.750000  24.000000  22.500000
std     3.559026   0.957427   0.816497   4.358899
min    22.000000  24.000000  23.000000  20.000000
25%    23.500000  24.000000  23.750000  20.000000
50%    26.500000  24.500000  24.000000  20.500000
75%    29.000000  25.250000  24.250000  23.000000
max    29.000000  26.000000  25.000000  29.000000

In [51]:
#adding a new column to dataframe
x = "aa bb cc dd".split()

In [52]:
df['newcolumn'] = x

In [54]:
df

cc1  cc2  cc3  cc4 newcolumn
rr1   29   25   25   20        aa
rr2   22   24   24   20        bb
rr3   29   26   24   29        cc
rr4   24   24   23   21        dd

In [55]:
#set_index() - It will set one specified column as index
df.set_index('newcolumn')

cc1  cc2  cc3  cc4
newcolumn                    
aa          29   25   25   20
bb          22   24   24   20
cc          29   26   24   29
dd          24   24   23   21

In [56]:
#reset_index() - 
df.reset_index()

index  cc1  cc2  cc3  cc4 newcolumn
0   rr1   29   25   25   20        aa
1   rr2   22   24   24   20        bb
2   rr3   29   26   24   29        cc
3   rr4   24   24   23   21        dd

In [57]:
#drop() - to delete a column

df.drop('newcolumn', axis =1)

cc1  cc2  cc3  cc4
rr1   29   25   25   20
rr2   22   24   24   20
rr3   29   26   24   29
rr4   24   24   23   21

In [58]:
#column deleted temporarily 
df

cc1  cc2  cc3  cc4 newcolumn
rr1   29   25   25   20        aa
rr2   22   24   24   20        bb
rr3   29   26   24   29        cc
rr4   24   24   23   21        dd

In [59]:
#drop() - to delete a column permanently
df.drop('newcolumn', inplace =True, axis=1)

In [60]:
df

cc1  cc2  cc3  cc4
rr1   29   25   25   20
rr2   22   24   24   20
rr3   29   26   24   29
rr4   24   24   23   21

In [61]:
#unique() - It gives all unique values
df['cc1'].unique()

array([29, 22, 24])

In [62]:
#value_counts() - In cc1 column, each value presented how many times it will give
df['cc1'].value_counts()

29    2
22    1
24    1
Name: cc1, dtype: int64

In [63]:
#create a sample dataset using numpy arrays
df = pd.DataFrame(np.random.rand(5,4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split())

In [64]:
df

W         X         Y         Z
A  0.704085  0.482732  0.073131  0.399759
B  0.090584  0.823094  0.797170  0.968882
C  0.567476  0.777768  0.811155  0.404694
D  0.500012  0.827396  0.555686  0.068475
E  0.175512  0.995090  0.349629  0.776174

In [65]:
df>0.4  #It return True or False 

W     X      Y      Z
A   True  True  False  False
B  False  True   True   True
C   True  True   True   True
D   True  True   True  False
E  False  True  False   True

In [66]:
#creating a new dataframe from an existing dataframe
df1 = df[df>0.4]

In [67]:
df1

W         X         Y         Z
A  0.704085  0.482732       NaN       NaN
B       NaN  0.823094  0.797170  0.968882
C  0.567476  0.777768  0.811155  0.404694
D  0.500012  0.827396  0.555686       NaN
E       NaN  0.995090       NaN  0.776174

In [68]:
#to check whether NaN values
df1.isnull().any

<bound method DataFrame.any of        W      X      Y      Z
A  False  False   True   True
B   True  False  False  False
C  False  False  False  False
D  False  False  False   True
E   True  False   True  False>

In [69]:
#for larger datasets
df1.isnull().any()  #It says at column level these columns has null values

W     True
X    False
Y     True
Z     True
dtype: bool

In [70]:
df1.isnull().sum() # it gives total number of null values

W    2
X    0
Y    2
Z    2
dtype: int64

In [71]:
#Method 1 - To handle missing values is drop them
#to drop the null values
df1.dropna() #bydefault axis = 0 and it will delete rowwise

W         X         Y         Z
C  0.567476  0.777768  0.811155  0.404694

In [72]:
df1.dropna(axis=1) # now it will delete columnwise

X
A  0.482732
B  0.823094
C  0.777768
D  0.827396
E  0.995090

In [73]:
df1   #temporary deletion happend in above 2 steps as we have not assigned to a new dataframe

W         X         Y         Z
A  0.704085  0.482732       NaN       NaN
B       NaN  0.823094  0.797170  0.968882
C  0.567476  0.777768  0.811155  0.404694
D  0.500012  0.827396  0.555686       NaN
E       NaN  0.995090       NaN  0.776174

In [74]:
df1.dropna(thresh = 2) #whereever NaN values are morethan 2 in a row only those rows got deleted

W         X         Y         Z
A  0.704085  0.482732       NaN       NaN
B       NaN  0.823094  0.797170  0.968882
C  0.567476  0.777768  0.811155  0.404694
D  0.500012  0.827396  0.555686       NaN
E       NaN  0.995090       NaN  0.776174

In [75]:
df1

W         X         Y         Z
A  0.704085  0.482732       NaN       NaN
B       NaN  0.823094  0.797170  0.968882
C  0.567476  0.777768  0.811155  0.404694
D  0.500012  0.827396  0.555686       NaN
E       NaN  0.995090       NaN  0.776174

In [76]:
df1.dropna(thresh =2, axis =1) #to delete column wise

W         X         Y         Z
A  0.704085  0.482732       NaN       NaN
B       NaN  0.823094  0.797170  0.968882
C  0.567476  0.777768  0.811155  0.404694
D  0.500012  0.827396  0.555686       NaN
E       NaN  0.995090       NaN  0.776174

In [77]:
df1

W         X         Y         Z
A  0.704085  0.482732       NaN       NaN
B       NaN  0.823094  0.797170  0.968882
C  0.567476  0.777768  0.811155  0.404694
D  0.500012  0.827396  0.555686       NaN
E       NaN  0.995090       NaN  0.776174

In [78]:
#Method 2 - Filling the missing values with some data
df1.fillna(value="nothing")

W         X         Y         Z
A  0.704085  0.482732   nothing   nothing
B   nothing  0.823094   0.79717  0.968882
C  0.567476  0.777768  0.811155  0.404694
D  0.500012  0.827396  0.555686   nothing
E   nothing  0.995090   nothing  0.776174

In [79]:
df1.fillna(value="0")

W         X         Y         Z
A  0.704085  0.482732         0         0
B         0  0.823094   0.79717  0.968882
C  0.567476  0.777768  0.811155  0.404694
D  0.500012  0.827396  0.555686         0
E         0  0.995090         0  0.776174

In [80]:
df1

W         X         Y         Z
A  0.704085  0.482732       NaN       NaN
B       NaN  0.823094  0.797170  0.968882
C  0.567476  0.777768  0.811155  0.404694
D  0.500012  0.827396  0.555686       NaN
E       NaN  0.995090       NaN  0.776174

In [81]:
df1.fillna(df['X'].mean())

W         X         Y         Z
A  0.704085  0.482732  0.781216  0.781216
B  0.781216  0.823094  0.797170  0.968882
C  0.567476  0.777768  0.811155  0.404694
D  0.500012  0.827396  0.555686  0.781216
E  0.781216  0.995090  0.781216  0.776174

In [82]:
df1

W         X         Y         Z
A  0.704085  0.482732       NaN       NaN
B       NaN  0.823094  0.797170  0.968882
C  0.567476  0.777768  0.811155  0.404694
D  0.500012  0.827396  0.555686       NaN
E       NaN  0.995090       NaN  0.776174

In [83]:
df2 = df1.fillna(df['X'].mean()) #permanent filling with mean value

In [84]:
df2

W         X         Y         Z
A  0.704085  0.482732  0.781216  0.781216
B  0.781216  0.823094  0.797170  0.968882
C  0.567476  0.777768  0.811155  0.404694
D  0.500012  0.827396  0.555686  0.781216
E  0.781216  0.995090  0.781216  0.776174